version: 2
jobs:
  build:
    docker:
      - image: golang:1.10-alpine
        environment:
          LUMBER_SERVER_ADDRESS: "http://127.0.0.1:8080"
          LUMBER_SESSION_TOKEN: "test"
      - image: takashabe/lumber-db-dev:2018-02-18-001714

    working_directory: /go/src/github.com/takashabe/lumber

    steps:
      - checkout

      - run:
          name: Install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.0

      - run:
          name: Wait for db startup
          command: |
            ./dockerize -wait tcp://localhost:3306 -timeout 1m

      - run:
          name: Install dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            make deps

      - run:
          name: Run unit test
          command: make test
